#!/usr/local/bin/php -Cq
<?php

/**
* Console script to generate MySQL plugins from command line
*
* @author Hartmut Holzgraefe <hartmut@six.de>
* @version $Id$
*/

// includes
require_once "CodeGen/Command.php";

require_once "CodeGen/MySQL/Plugin/Extension.php";
require_once "CodeGen/MySQL/Plugin/ExtensionParser.php";
#require_once "CodeGen/Element.php";

// create extension object
$extension = new CodeGen_MySQL_Plugin_Extension;

$command = new CodeGen_Command($extension);

$parser = new CodeGen_MySQL_Plugin_ExtensionParser($extension);

$command->execute($parser);

?>
